verbosity: 1
images:
  cdi:
    repositoryPrefix: kubevirt
    tag: v1.13.0
    pullPolicy: IfNotPresent
  hyperkube:
    repository: k8s.gcr.io/hyperkube
    tag: v1.12.1
    pullPolicy: IfNotPresent
