# Deleting CR
# See link: https://github.com/helm/charts/blob/d58247103fafd5930792bb1fd3ac240547523200/stable/prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml#L33
apiVersion: batch/v1
kind: Job
metadata:
  name: cdi-pre-delete
  # TODO: Make serviceaccount for this
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: cdi-pre-delete
    spec:
      serviceAccountName: default
      containers:
        - name: kubectl
          image: {{ .Values.images.hyperkube.repository }}:{{ .Values.images.hyperkube.tag }}
          imagePullPolicy: {{ .Values.images.hyperkube.pullPolicy }}
          command:
          - /bin/sh
          - -c
          - >
              kubectl delete --all -n cdi cdis.cdi.kubevirt.io;
      restartPolicy: OnFailure
